### ISSUE TITLE
Enable Foreign Keys on connection?

### ISSUE THREAD

**Issue by captainswain** [mcfunley/pugsql#24]
Hi there,

I was wondering if there is an easy way with pugsql to run "PRAGMA foreign_keys = ON;" on the inital connection.

is my best bet just to create a query and run it that way?

**Comment by mcfunley** [comment]
Hey it seems like this would work, since you 

https://stackoverflow.com/a/2615603

If you did that then you can use [set_engine](https://pugsql.org/doc/0.1.15/pugsql/compiler.html#pugsql.compiler.Module.set_engine) to pass the engine to a pugsql module, rather than using `connect` with a connection string.

```python
engine = thing_to_create_engine_with_pragma()
queries = pugsql.module(path)
queries.set_engine(engine)
```
